# Site settings
name: Guo Zhang
email: zhangguo@stu.xmu.edu.cn
author: Guo Zhang
url: http://zhangguo.me

github: https://github.com/Guo-Zhang
linkedin: https://www.linkedin.com/in/zhangguo
zhihu: https://www.zhihu.com/people/zhang_guo

baseurl: ""
description: Founder, Chairman and CEO, China's Prices Project (QuantTide Inc.)
meta_description: Guo Zhang
motto: Guo Zhang
banner: Founder, Chairman and CEO, China's Prices Project (QuantTide Inc.)

# permalink: /:categories/:year/:month/:day/:title/
# permalink: /:year/:month/:day/:title/
# permalink: /blog/:categories/:title
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','run.bat','run.sh','help.md']

github_username: Guo-Zhang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : iGuo
    disqus :
        short_name : iGuo
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light