# Site settings
name: Guo Zhang
email: zhangguo@stu.xmu.edu.cn
author: Guo Zhang
url: http://zhangguo.github.io

linkedin: https://www.linkedin.com/in/zhangguo
github: https://github.com/Guo-Zhang
zhihu: https://www.zhihu.com/people/zhang_guo

baseurl: ""
description: Third-year Undergraduate of WISE, Xiamen University
meta_description: Guo Zhang
motto: Guo Zhang
banner: WISE, Xiamen University

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','run.bat','help.md']

github_username: Guo-Zhang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light